
head(cons(zero, nil), zero)?
tail(cons(zero, nil), nil)?
head(cons(succ(zero), nil), succ(zero))?
tail(cons(succ(zero), nil), nil)?
head(cons(succ(zero), cons(zero, nil)), succ(zero))?
tail(cons(succ(zero), cons(zero, nil)), cons(zero, nil))?


head(cons(zero, nil), zero).
tail(cons(zero, nil), nil).
head(cons(succ(zero), nil), succ(zero)).
tail(cons(succ(zero), nil), nil).
head(cons(succ(zero), cons(zero, nil)), succ(zero)).
tail(cons(succ(zero), cons(zero, nil)), cons(zero, nil)).

head(cons(zero, nil), zero)?
tail(cons(zero, nil), nil)?
head(cons(succ(zero), nil), succ(zero))?
tail(cons(succ(zero), nil), nil)?
head(cons(succ(zero), cons(zero, nil)), succ(zero))?
tail(cons(succ(zero), cons(zero, nil)), cons(zero, nil))?

