p("eh"
, "bee", 

"another string"


)

.

p(
"oh"

,


 "huh?"
).

qpred("one", "two", "three").
qpred("one", "two", "three", "one", "two", "three", "one", "two", "three", "one", "two", "three").
qpred("one", "two", "three", "one", "two", "three", "one", "two", "three", "one", "two", "three",
"one", "two", "three", "one", "two", "three", "one", "two", "three", "one", "two", "three",
"one", "two", "three", "one", "two", "three", "one", "two", "three", "one", "two", "three",
"one", "two", "three", "one", "two", "three", "one", "two", "three", "one", "two", "three").
