p("eh"
, "bee", 

"another string"


)

.

p("eh"
, "bee", 

"another string"


)

?

p(
"oh"

,


 "huh?"
).

p(
"oh"

,


 "huh?"
)?

qpred("one", "two", "three").
qpred("one", "two", "three", "one", "two", "three", "one", "two", "three", "one", "two", "three").
qpred("one", "two", "three", "one", "two", "three", "one", "two", "three", "one", "two", "three",
"one", "two", "three", "one", "two", "three", "one", "two", "three", "one", "two", "three",
"one", "two", "three", "one", "two", "three", "one", "two", "three", "one", "two", "three",
"one", "two", "three", "one", "two", "three", "one", "two", "three", "one", "two", "three").



qpred("one", "two", "three")?
qpred("one", "two", "three", "one", "two", "three", "one", "two", "three", "one", "two", "three")?
qpred("one", "two", "three", "one", "two", "three", "one", "two", "three", "one", "two", "three",
"one", "two", "three", "one", "two", "three", "one", "two", "three", "one", "two", "three",
"one", "two", "three", "one", "two", "three", "one", "two", "three", "one", "two", "three",
"one", "two", "three", "one", "two", "three", "one", "two", "three", "one", "two", "three")?
